#!/bin/ksh
#

set -xv

#  RUN_STR

#

SCR_NAME=REPORT_BIAS
SCR_PARM=0
SCR_LIST="CASE ETA_IN"
SCR_VERS=070928.0

SCR_DBG="#"
export SCR_DBG

if [ `expr $#` -lt $SCR_PARM ]; then
   echo "Usage: $SCR_NAME ${SCR_LIST}\007"
   exit 101
fi

Date=`date +%y%m%d`

DateTime=`date '+DATE: %m/%d/%y  TIME: %H:%M:%S'`

echo " # "
echo " #  $SCR_NAME $* "
echo " # "
echo " #  Version $SCR_VERS "
echo " # "
echo " #  Run Date $DateTime "
echo " # "
disk_P1=/umbc/epavlis/data01/LOCAL/magdak
disk=/afs/umbc.edu/users/m/a/magdak/home
SCRIPTS=/umbc/epavlis/data01/LOCAL/magdak/scripts/OPS
SCRIPTS=/afs/umbc.edu/users/m/a/magdak/home/scripts/OPS
export SCRIPTS disk
CASE=WEEKLY
DELTA=7

read YEAR ODOY DATE ARC < $disk_P1/INFILES/INF_OPS_ITRF2020/ARC_SETUP_NEW.WEEKLY_v80
 NDATE=$(date +%Y-%m-%d -d "$DATE")
psql -t -h localhost -U jasongroup -d noofobs --command "delete from l1_w where obs_date='$NDATE';" > t43
psql -t -h localhost -U jasongroup -d noofobs --command "delete from l2_w where obs_date='$NDATE';" >> t43
psql -t -h localhost -U jasongroup -d noofobs --command "delete from e1_w where obs_date='$NDATE';" >> t43
psql -t -h localhost -U jasongroup -d noofobs --command "delete from e2_w where obs_date='$NDATE';" >> t43

print "REMOVE from DATABSE noofobs" > t43.txt
cat t43 >> t43.txt
mailx -s "REMOVE from DATABSE noofobs" magdak@umbc.edu < t43.txt 


exit 0

