#!/bin/bash

# Loop to run the command 77 times
#for ((i=1; i<=77; i++))
for ((i=1; i<=40; i++))
do
    # Run the command
    ./RUN_SERIES_IERS_SLRF2020_7d+satIDir_2024_02_06_test_v280 WEEKLY YES OPS2020 . 280 >&! o.WEEKLY_v280_$i

    # Sleep for a second before running the next iteration (if needed)
    sleep 1
done

