#!/bin/ksh
#
set -xv

#  RUN_STR

#

SCR_NAME=plots
SCR_PARM=0
SCR_LIST="CASE ETA_IN"
SCR_VERS=080805.0

SCR_DBG="#"
export SCR_DBG

if [ `expr $#` -lt $SCR_PARM ]; then
   echo "Usage: $SCR_NAME ${SCR_LIST}\007"
   exit 101
fi

Date=`date +%y%m%d`

DateTime=`date '+DATE: %m/%d/%y  TIME: %H:%M:%S'`

echo " # "
echo " #  $SCR_NAME $* "
echo " # "
echo " #  Version $SCR_VERS "
echo " # "
echo " #  Run Date $DateTime "
echo " # "


MAIN_PATH=/umbc/epavlis/data01/LOCAL/magdak
CASE=plots
#mkdir -p /tmp/magdak
#chmod -R 775 /tmp/magdak
cd /tmp/magdak
mkdir ${CASE}$$
cd ${CASE}$$
cp $MAIN_PATH/INFILES/INF_OPS_LARES/*plt /tmp/magdak/${CASE}$$
export SCRIPTS
#####


ARC1=$1
SAT=$2
ARC2=${ARC1}

ARC=${ARC1}_pbias
cp Res_per_pas_LE_P2.plt Res_per_pas.plt
#zcat $MAIN_PATH/MISSIONS/$SAT/residuals_ascii/DR/DAILY/${ARC1}.wT1.sort_by_config.gz > T1A



cat $MAIN_PATH/MISSIONS/$SAT/residuals_ascii_xtnd/EMT/DAILY/v${SNX_VER}/${ARC1}.wv${SNX_VER}e.resxtnd > t1
#new
 cut -c1-86,115-150 t1 > T1

#
cut -c26-33 T1 > T2
sort -u T2 > T3

printf "gs -dBATCH -dNOPAUSE -q -sDEVICE=pdfwrite -sOutputFile=REPORT_${SAT}_${ARC1}.pdf" > P2

while read STA 
do
printf "gs -dBATCH -dNOPAUSE -q -sDEVICE=pdfwrite -sOutputFile=REPORT_${SAT}_${STA}_${ARC1}.pdf" > PP2

cp  $MAIN_PATH/MISSIONS/$SAT/products/arc/DAILY/v${SNX_VER}/${ARC1}_pbias.wv${SNX_VER}P  PB1
grep "$STA" T1 > PB2
cut -c17-25 PB2 > PB4
sort -u PB4 > PB5  
read NAME < PB5
grep "$NAME" PB1 > PB6
grep "B051000" PB6 > PB7
#PB7 contain value PBIAS51 card for station 
pwd
### NEW mkc 1701307
mkdir /umbc/epavlis/data01/LOCAL/magdak/MISSIONS/PASS/$SAT/${ARC}
cp pass_num1 /umbc/epavlis/data01/LOCAL/magdak/MISSIONS/PASS/$SAT/${ARC}/pass_num1_${STA}_${ARC}
####




rm  /tmp/magdak/${CASE}$$/res1a
rm  /tmp/magdak/${CASE}$$/res1a.gz
rm -rf /tmp/magdak/${CASE}$$/res1
mkdir res1
rm -f RTime T1a T1b T1c T1d T2d T3d T4d  res1a

zgrep "Reference Time" /umbc/epavlis/data01/LOCAL/magdak/MISSIONS/$SAT/residuals_ascii/DR/DAILY/v${SNX_VER}/${ARC}.wv${SNX_VER}P.sort_by_config.gz > RTime
cat RTime > res1a
grep "$STA" T1 >> res1a

grep -v "  -1.000" res1a > res
#I lost i whene I delete sourcea $MAIN_PATH/EXECUTABLES/CRD_LE_181001.x
$MAIN_PATH/EXECUTABLES/CRD_LE_221205.x

mv mean_res_per_pass mean_res_per_pass_$STA
mv ????????_??? mean* res_p* res1/.
pwd
mv pass_nu pass_num1


NUM0=0

while read  S11 S12 S13 STD1 MEAN1 RMS1 OBS1 MIN1 MAX1 #NUM1
do

    NUM0=`expr $NUM0 + 1`
    NUM1=$(printf "%03d" $NUM0)
cp res1/${STA}*_$NUM1 F1 

#MAX2=$(echo "( ${MAX1} + 2 ) + 0.25 * ( ( ${MAX1} + 2 ) - ( ${MIN1} - 2 ) )"  | bc )
MAX2=$(echo "( ( ${MAX1} + 2 ) + 0.25 * ( ${MAX1}  - ${MIN1}  ) ) / 1"  | bc )
MIN2=$(echo " ( ${MIN1} - 2 ) / 1 "  | bc )



# PUT statistic to gnuplot script
sed "s/CCCCCCCCCCCC/$MEAN1/g"  Res_per_pas.plt >  t0a
sed "s/DDDDDDDDDDDD/$STD1/g"  t0a >  t0b
sed "s/EEEEEEEEEEEE/$RMS1/g"  t0b >  t0c

sed "s/IIIIIIIIIIII/${STA}/g"   t0c >  t0g


#put name station and name file to gnuplot script
sed "s/SSSS/$SAT/g"  t0g >  t0n
sed "s/AAAAAAAAAAA/F1/g"  t0n >  t0o 
sed "s/MAX/$MAX2/g"  t0o >  t0p 
sed "s/MIN/$MIN2/g"  t0p >  t0

#sed -n "1,1p" $FILE > t0
sed -n "1,1p" F1 > t1

# put start and stop time to gnuplot script
cut -c12-15 t1 > YYYY
cut -c17-18 t1 > MM
cut -c20-21 t1 > DD
cut -c23-24 t1 > HH
cut -c26-27 t1 > MMM

read YYYY1 < YYYY
read MM1 < MM
read DD1 < DD
read HH1 < HH
read MMIA < MMM

$MAIN_PATH/scripts/ymd2ydoy $YYYY1 $MM1 $DD1  > DAT
cut -c1-2 DAT > YYYY
cut -c3-5 DAT > IDOY 
read YYYY < YYYY
read IDOY < IDOY
MMIA=`expr ${MMIA} - 1`
if [ "$MMIA" -lt "10" ]; then
printf "0$MMIA" > DD
read MMIA < DD
fi
while read A1 A2 A3 A4 
do
printf $A3 > HM
printf $A2 > YMD
#done <  $FILE
done <  F1
cut -c1-4 YMD >YYY
cut -c6-7 YMD > MMM 
cut -c9-10 YMD > DDD 
cut -c1-2 HM > HHH  
cut -c4-5 HM > MMI 
read YYYY2 < YYY
read DD2 < DDD
read MM2 < MMM
read HH2 < HHH
read MMIB < MMI
MMIB=`expr ${MMIB} + 1`
if [ "$MMIB" -lt "10" ]; then
printf "0$MMIB" > DD
read MMIB < DD
fi
cut -c1-2 DAT2 > YYYY
cut -c3-4 DAT2 > MM
cut -c5-6 DAT2 > DD
sed "s/YEARCURRENT/$YYYY1/g" t0 > t00
sed "s/YYYY1/$YYYY1/g"  t00 >  t01
sed "s/MM1/$MM1/g"  t01 > t02
sed "s/DD1/$DD1/g"  t02 > t03
sed "s/HH1/$HH1/g"  t03 > t04
sed "s/YYYY2/$YYYY2/g"  t04 >  t05 
sed "s/MM2/$MM2/g"  t05 > t06
sed "s/DD2/$DD2/g"  t06 > t07
sed "s/HH2/$HH2/g"  t07 >  t08
sed "s/MMIA/$MMIA/g"  t08  > t09
sed "s/MMIB/$MMIB/g"  t09 > Mean_res_${STA2}.plt 
	gnuplot  Mean_res_${STA2}.plt

#if [ -s Res.eps ]; then
if [ -s Res.pdf ]; then
cp Res.pdf Res_${NUM1}_${ARC1}_${STA2}.pdf
#epstopdf -d --nogs -hires  Res.eps >  Res_${NUM1}_${ARC1}_${STA2}.ps
#ps2pdf  Res_${NUM1}_${ARC1}_${STA2}.ps
#printf "  Res_${NUM1}_${ARC1}_${STA2}.pdf" >> P2
printf "  Res_${NUM1}_${ARC1}_${STA2}.pdf" >> PP2
fi
#cp Mean_res_70802419.plt Res_${NUM1}_${ARC1}_${STA2}.plt 
rm t* D* Y* MM*

done < res1/mean_res_per_pass_${STA}


### NEW mkc 1701307
#cat /umbc/epavlis/data01/LOCAL/magdak/MISSIONS/PASS/$SAT/${ARC}/pass_num1_*_${ARC} > /umbc/epavlis/data01/LOCAL/magdak/MISSIONS/PASS/$SAT/${ARC}/ALL_$SAT
#
#NUM=0
#while read NUM0
#do
#NUM=`expr ${NUM} + ${NUM0}`
#done < /umbc/epavlis/data01/LOCAL/magdak/MISSIONS/PASS/$SAT/${ARC}/ALL_${SAT}
#NEW 170308 mkc
grep B051  $MAIN_PATH/MISSIONS/$SAT/products/arc/DAILY/v${SNX_VER}/${ARC}.wv${SNX_VER}P > PB51
mkdir $MAIN_PATH/MISSIONS/PASS/$SAT/${ARC}
#cp PB51 $MAIN_PATH/MISSIONS/PASS/$SAT/${ARC}/pass_num1_${STA}_${ARC}
wc -l PB51 > PB51_NUM
read NUM FF < PB51_NUM

if   [ "$SAT" = "GISL1" ];then
    SV=L1
elif [ "$SAT" = "GISL2" ];then
   SV=L2
elif [ "$SAT" = "LARES" ];then
   SV=LARES
elif [ "$SAT" = "ETA1" ];then
    SV=E1
elif [ "$SAT" = "ETA2" ];then
	   SV=E2
fi
echo "${SV}   $NUM " > /tmp/magdak/ALL_${ARC}_${SV}
#exit 221207
#### 
mv STAT2_$STAT
rm STAT2
chmod 775 P2
chmod 775 PP2
#./P2
./PP2

mkdir /umbc/epavlis/data01/LOCAL/magdak/MISSIONS/PLOTS
mkdir /umbc/epavlis/data01/LOCAL/magdak/MISSIONS/PLOTS/${ARC}
mkdir /umbc/epavlis/data01/LOCAL/magdak/MISSIONS/PLOTS/${ARC}/${STA2}

cp  REPORT_${SAT}_${STA}_${ARC1}.pdf  $MAIN_PATH/MISSIONS/PLOTS/${ARC}/${STA2}/.

done < T3

ls -1 REPORT_${SAT}_????????_${ARC1}.pdf > P3
while read file
do
printf "  $file" >> P2
done < P3
./P2  
cp  REPORT_${SAT}_${ARC1}.pdf  $MAIN_PATH/tmp/magda/${TT}/DAILY/${Date_NEW_ARC}/.
cd ..
#\rm -r ${CASE}$$  
exit 0


