#!/bin/ksh
#

set -xv

#  RUN_SERIES_IERS_SLRF2020_7d+satIDir      


SCR_NAME=RUN_SERIES_IERS_SLRF2020_7d+satIDir_2024_02_06        
SCR_PARM=0
SCR_LIST="CASE ETA_IN GROUP JOB_FILE RUN_NUMBER RUN_YEAR MDLS"
SCR_VERS=240206.0

SCR_DBG="#"
export SCR_DBG

if [ `expr $#` -lt $SCR_PARM ]; then
   echo "Usage: $SCR_NAME ${SCR_LIST}\007"
   exit 101
fi

Date=`date +%y%m%d`

DateTime=`date '+DATE: %m/%d/%y  TIME: %H:%M:%S'`

echo " # "
echo " #  $SCR_NAME $* "
echo " # "
echo " #  Version $SCR_VERS "
echo " # "
echo " #  Run Date $DateTime "
echo " # "



SCRIPTS=/umbc/epavlis/data01/LOCAL/magdak/scripts/ITRF2020/OPS/
while read ARC
do
$SCRIPTS/ADD_PSD_CORRECTED_EPOCH_ITRF2020_221213  $ARC > o.ADD_PSD_CORRECTED_EPOCH_ITRF2020 2>&1
$SCRIPTS/ADD_PSD_CORRECTED_MID_ARC_ITRF2020_221213  $ARC > o.ADD_PSD_CORRECTED_MID_ARC_ITRF2020 2>&1
done < ARC_LIST_ADD
exit 0
