#!/bin/ksh
#

set -xv

#  RUN_SERIES_IERS_SLRF2020_7d+satIDir      


SCR_NAME=RUN_QC_7306        
SCR_PARM=0
SCR_LIST="CASE ETA_IN GROUP JOB_FILE RUN_NUMBER RUN_YEAR MDLS"
SCR_VERS=230709.0

SCR_DBG="#"
export SCR_DBG

if [ `expr $#` -lt $SCR_PARM ]; then
   echo "Usage: $SCR_NAME ${SCR_LIST}\007"
   exit 101
fi

Date=`date +%y%m%d`

DateTime=`date '+DATE: %m/%d/%y  TIME: %H:%M:%S'`

echo " # "
echo " #  $SCR_NAME $* "
echo " # "
echo " #  Version $SCR_VERS "
echo " # "
echo " #  Run Date $DateTime "
echo " # "


CASE=DAILY
ETA_IN=NO
GROUP=OPS2020
JOB_FILE=.
SNX_VER=180
STAION=7306
MAIN_PATH=/umbc/epavlis/data01/LOCAL/magdak
infile=/umbc/epavlis/data01/LOCAL/magdak/INFILES/START-STOP_DATES.7306_231116
infile=/umbc/epavlis/data01/LOCAL/magdak/INFILES/START-STOP_DATES.7306_240312 
infile=/umbc/epavlis/data01/LOCAL/magdak/INFILES/START-STOP_DATES.7306_240321 
while read   ARC A1
do

Date_NEW_ARC=$A1
YY=`echo ${Date_NEW_ARC}|cut -c1-2`
if [ "$YY" -gt "50" -a "$YY" -le "99" ];then

 arc_yy=`expr $YY + 1900`

 elif [ "$YY" -ge "00" -a "$YY" -le "50" ];then

  arc_yy=`expr $YY + 2000`

  fi
NYEAR=$arc_yy
export  Date_NEW_ARC NYEAR
exec > /umbc/epavlis/data01/LOCAL/magdak/tmp/${SCR_NAME}.${CASE}_${ARC}_$Date.$$.log 2>&1

EFFORT=POS+EOP

ITRF_APRIORI=SLRF2020

export GROUP EFFORT ITRF_APRIORI

#DHFile_REPRO=ILRS_Data_Handling_File_REPRO2020_210416.snx
DHFile_REPRO=ILRS_Data_Handling_File_2023.06.21.snx

export DHFile_REPRO

# Define the Target Signature Correction (TSC) Model version 
# for CoG Block creation:

TSC_MODEL=NERC220915

export TSC_MODEL

MAIN_PATH=/umbc/epavlis/data01/LOCAL/magdak
MAIN_PATH_OLD=/umbc/epavlis/data01/LOCAL/magdak
SCRIPTS=$MAIN_PATH/scripts/ITRF2020/OPS
DISK=$MAIN_PATH/MISSIONS
disk_n=$MAIN_PATH
disk_s=$MAIN_PATH/MISSIONS


#191120 CORRECT MBIAS 300

#PL GDN_2S=gs1810p3_i64+1.x
#PL GDN_2E=ge1810p09_i64_PLD.x

 GDN_2S=PE2_EXECi64/gs1810p2_i64_PE2.x
 GDN_2E=PE2_EXECi64/ge1810p09_i64_PE2.x



#EOP 230102
RUN_GDN_SLR_SCR=RUN_GDN_SLR_2023
export GDN_2S GDN_2E disk_s disk_n RUN_GDN_SLR_SCR MAIN_PATH 


# This means that the file with the arcs to run, the "JOB_FILE" will be:


RUN_FILE=${JOB_FILE}.${EFFORT}.$GROUP



if [ "$CASE" = "WEEKLY" ]; then

  ARC_LEN=8
  ARC_LEN=7
  DELTA=7
  ACCEL_NUM_L=2
  ACCEL_NUM_E=1
  LVER=wv415  
  LVER=wv${SNX_VER} 
  TYPE_DR=DRWC
  TYPE_EMT=EMTWC
  WEIGHT=100
  WEIGHT=


  SNX_VER2=$SNX_VER

#  ATTENTION:    Is this right for these series?   YES !!!  This means that E1 & E2 MBIAS 51 are COMBINED to EC !!!

if [ "$SNX_VER" = "415" ]; then

  BIAS=7

fi
if [ "$SNX_VER" = "232" ]; then

  BIAS=7

fi

export SNX_VER SNX_VER2 BIAS

if [ "$SNX_VER" = "80"  -o "$SNX_VER" = "180" ]; then

#GRAV_TOP=GRAVTOP_JCET@2010.0_G210101-G300108 
GRAV_TOP=GRVEPO_100101
GRAVITY_MDL=GGM05C_30x30
GRVTIM=JCET_CURRENT_GSM+GAC_20x20

#HF MDL (HFEOP11)
ETIDE_MDL=TIDES+etides_RAY_2018
OTIDE_MDL=GOT4.10/20otides_got4p10c+Air_Tides_got4.7
OLOAD_MDL=got4p10c.2014.ocean_loading_values_without_CMC_2024.gdyn
HFCOM_MDL=HFCOM/HFCOM_GOT4.10c
HFEOP_MDL=HFEOP/HFEOP_DESAIwLib

 elif  [ "$SNX_VER" = "280"  -o "$SNX_VER" = "230" ]; then
#GRAV_TOP=GRAVTOP_JCET@2010.0_G210101-G300108
GRAV_TOP=GRVEPO_100101
GRAVITY_MDL=GGM05C_30x30
GRVTIM=JCET_CURRENT_GSM+GAC_20x20

#HF MDL (HFEOP11)
ETIDE_MDL=TIDES+etides_RAY_2018
OTIDE_MDL=GOT4.10/20otides_got4p10c+Air_Tides_got4.7
OLOAD_MDL=got4p10c.2014.ocean_loading_values_without_CMC_2024.gdyn
HFCOM_MDL=HFCOM/HFCOM_GOT4.10c
HFEOP_MDL=HFEOP/HFEOP_DESAIwLib

 fi

  export GRAVITY_MDL GRVTIM GRAV_TOP  
  export ETIDE_MDL OTIDE_MDL HFEOP_MDL HFCOM_MDL OLOAD_MDL


  CURRENT_APLO=050210

  export CURRENT_APLO

  IERS_CPP_CENTER=JCT
  IERS_CPP_TECHNQ=L
  IERS_CPP_LENGTH=7
  OUR_VERSION=30

  export IERS_CPP_CENTER IERS_CPP_TECHNQ IERS_CPP_LENGTH OUR_VERSION
 elif [ "$CASE" = "DAILY" ]; then

  ARC_LEN=7
  DELTA=1
  ACCEL_NUM_L=2
  ACCEL_NUM_E=1
  LVER=wv180  
  LVER=wv${SNX_VER} 
  TYPE_DR=DRWC
  TYPE_EMT=EMTWC
  WEIGHT=100
  WEIGHT=


  SNX_VER2=$SNX_VER

#  ATTENTION:    Is this right for these series?   YES !!!  This means that E1 & E2 MBIAS 51 are COMBINED to EC !!!

if [ "$SNX_VER" = "415" ]; then

  BIAS=7

fi
if [ "$SNX_VER" = "232" ]; then

  BIAS=7

fi

export SNX_VER SNX_VER2 BIAS


#GRAV_TOP=GRAVTOP_JCET@2010.0_G210101-G300108 
GRAV_TOP=GRVEPO_100101
GRAVITY_MDL=GGM05C_30x30
GRVTIM=JCET_CURRENT_GSM+GAC_20x20

  export GRAVITY_MDL GRVTIM GRAV_TOP  



###
#HF MDL (HFEOP11)
###

    ETIDE_MDL=TIDES+etides_RAY_2018
    OTIDE_MDL=GOT4.10/20otides_got4p10c+Air_Tides_got4.7
    OLOAD_MDL=got4p10c.2014.ocean_loading_values_without_CMC_2024.gdyn
    HFCOM_MDL=HFCOM/HFCOM_GOT4.10c
    HFEOP_MDL=HFEOP/HFEOP_DESAIwLib

  export ETIDE_MDL OTIDE_MDL HFEOP_MDL HFCOM_MDL OLOAD_MDL


  CURRENT_APLO=050210

  export CURRENT_APLO

  IERS_CPP_CENTER=JCT
  IERS_CPP_TECHNQ=L
  IERS_CPP_LENGTH=7
  OUR_VERSION=30

  export IERS_CPP_CENTER IERS_CPP_TECHNQ IERS_CPP_LENGTH OUR_VERSION

elif [ "$CASE" = "MONTHLY" ]; then

  ARC_LEN=28
  DELTA=28
  ACCEL_NUM_L=7
  ACCEL_NUM_E=4
  LVER=m
  TYPE_DR=DRM
  TYPE_EMT=EMTM

  if [ "$MDLS" = "1810" ]; then

    ETIDE_MDL=TIDES+etides_RAY_2018.fxd
    OTIDE_MDL=GOT4.10/20otides_got4p10c+Air_Tides_got4.7.fxd
    HFEOP_MDL=di+semidiurnal_tidal_EOP_2018
    HFCOM_MDL=di+semidiurnal_tidal_COM_GOT4.10c
    OLOAD_MDL=got4p10c.2014.ocean_loading_values_without_CMC_2024.gdyn
  
  fi

  export ETIDE_MDL OTIDE_MDL HFEOP_MDL HFCOM_MDL OLOAD_MDL

  CURRENT_APLO=050210

  export CURRENT_APLO

fi

 cd $MAIN_PATH/tmp/magda
wkTmp=$$
mkdir ${CASE}${wkTmp}_${ARC}
cd $MAIN_PATH/tmp/magda/${CASE}${wkTmp}_${ARC}
TT=${CASE}${wkTmp}_${ARC}
 export TT

#  Read the CONFIG file to find out the LVPARM and Unit 5 files to use in SOLVE:

read INTPRM INTU5 < $MAIN_PATH/INFILES/${EFFORT}.${GROUP}.CONFIG.${CASE}

export INTPRM INTU5


echo ${CASE}${wkTmp} > $MAIN_PATH/tmp/magda/${CASE}_wDIR_$Date

DIR_2_TAR=${CASE}_wDIR_$Date
CDIR=$MAIN_PATH/tmp/magda/${CASE}${wkTmp}$A3
export DIR_2_TAR CDIR

SERVICE=ILRS
ILRS_AC=jcet


ITR=0
VER=${LVER}e
GTR=3
PROJ=.
SUBSOL=.
DELETE=OUT
INSERT=NONE


export CASE ARC_LEN ACCEL_NUM_L ACCEL_NUM_E DELTA MAIN_PATH MAIN_PATH_OLD SCRIPTS SNX_VER ETA_IN

export ITR LVER VER GTR PROJ SUBSOL DELETE INSERT SERVICE DISK WEIGHT ILRS_AC wkTmp







#
#------------------------------------------------
#  Propagate the Sites' file to the Mid-Arc Epoch:
#------------------------------------------------
#


  ITRF_2_PROPAGATE=$ARC

  export ITRF_2_PROPAGATE

$SCRIPTS/ADD_PSD_CORRECTED_EPOCH_ITRF2020_240312_7306  ${ARC}_pbias_7306 > o.ADD_PSD_CORRECTED_EPOCH_ITRF2020 2>&1
$SCRIPTS/ADD_PSD_CORRECTED_MID_ARC_ITRF2020_240312_7306  ${ARC}_pbias_7306 > o.ADD_PSD_CORRECTED_MID_ARC_ITRF2020 2>&1
 
#exit 
#
#----------------------------------------------
#  Now generate the arc-setups for the new arcs:
#----------------------------------------------
#
#
#  For each S/C go through the following steps:
#
# a) turn last arc (from EMT punch, i.e. EMT2DR) and save ELEMS records
#
# b) using above ELEMS and template, make new arc
#
# c) run the new arc (DR)
#
# d) turn the punch and re-run (DR) the arc
#
# e) turn the punch for EMAT and cut two EMATs, one for operational
#    and one for the re-analysis series
#
# f) Update the Solution Number for this week
#
#----------------------------------------------
#



SUBDIR=OPS
export SUBDIR



#---------------------------------------------------


#  Process QC LAGEOS  1 & 2


#---------------------------------------------------




#---------------------------------------------------


#QC
##BIAS REPORT

#---------------------------------------------------
cd $MAIN_PATH/tmp/magda/${CASE}${wkTmp}_${ARC}
######
######
#LAGEOS 1
SVN=L1
SAT=GISL1
#$SCRIPTS/REPORT_BIAS_2023_RE_RUN_v70 ${ARC} $SAT ${LVER}  $YY $TYPE_DR $SVN $STAION > o.REPORT_BIAS_${SAT} 2>&1
 $SCRIPTS/REPORT_BIAS_2023_R ${ARC} $SAT ${LVER}  $YY $TYPE_DR $SVN > o.REPORT_BIAS_${SAT} 2>&1
#230928 -only missing L2 $SCRIPTS/REPORT_BIAS_2023_RE_RUN ${ARC} $SAT ${LVER}  $YY $TYPE_DR $SVN $STAION > o.REPORT_BIAS_${SAT} 2>&1 &
#exit 0 
#LAGEOS 2
SVN=L2
SAT=GISL2
#$SCRIPTS/REPORT_BIAS_2023_RE_RUN_v70 ${ARC} $SAT ${LVER}  $YY $TYPE_DR $SVN $STAION > o.REPORT_BIAS_${SAT} 2>&1
 $SCRIPTS/REPORT_BIAS_2023_R ${ARC} $SAT ${LVER}  $YY $TYPE_DR $SVN > o.REPORT_BIAS_${SAT} 2>&1
# exit 0
 done < $infile
exit 0

